### ISSUE TITLE
hey, can you help me with this? ty

### ISSUE THREAD

**Issue by tfanshool** [VikashOraon/CollegeMiniProject#1]
1st, where is the 'db.php'?

![image](https://user-images.githubusercontent.com/79323386/110969761-11f0a180-837f-11eb-9086-0395f6d65efc.png)
![image](https://user-images.githubusercontent.com/79323386/110970082-64ca5900-837f-11eb-871e-11913616c29f.png)

The same goes with header.php

**Comment by VikashOraon** [comment]
forgot to upload  the 'include' folder!!!
